// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TJSGB9-5s-5wYl1UGtbPrG_n-Kiui4w',
    appId: '1:897832137391:web:ac7548e1309c17e129da5a',
    messagingSenderId: '897832137391',
    projectId: 'tuguiapp-5364f',
    authDomain: 'tuguiapp-5364f.firebaseapp.com',
    storageBucket: 'tuguiapp-5364f.firebasestorage.app',
    measurementId: 'G-FR5CWNG90F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8b8-a5EmSe0hmk52-JwQMc8sS4IPPb9A',
    appId: '1:897832137391:android:71fec2565c47cc5929da5a',
    messagingSenderId: '897832137391',
    projectId: 'tuguiapp-5364f',
    storageBucket: 'tuguiapp-5364f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy8y5Ujfa2vOPXaxO5tPFU_xT2IYiR0Sk',
    appId: '1:897832137391:ios:9dc484de79fe602f29da5a',
    messagingSenderId: '897832137391',
    projectId: 'tuguiapp-5364f',
    storageBucket: 'tuguiapp-5364f.firebasestorage.app',
    iosBundleId: 'com.example.ubiTramite',
  );
}
